apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: avigoldshtein-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: avigoldshtein/python-app:latest  # החליף את זה בתמונה שלך
        env:
        - name: MYSQL_HOST
          value: mysql.avigoldshtein-dev.svc.cluster.local
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user_password
        - name: MYSQL_DATABASE
          value: mydb
        ports:
        - containerPort: 8000  # אם זה FastAPI או Flask
